@startmindmap
'https://plantuml.com/mindmap-diagram

caption CHAPTER 2
title 数据模型与查询语言

* 第二章
** 可靠性-Reliability
*** 以最小出错的方式来设计系统
*** 功能齐全但非生产用的沙箱环境
*** 充分的测试
**** 测试工具: Netflix Chaos Monkey Test
**** 从单元测试 -> 全系统功能测试 -> 手动测试

** 可扩展性-Scalability
*** 系统负载 & 性能
**** 负载增加，系统资源不变，则性能下降
**** 负载增加，如果要保持性能不变，肯定要增加系统资源
*** 应对负载增加的办法
**** 垂直扩展：提高单个实例的性能
**** 水平扩展：将负载分布到多个更小的机器

** 可维护性-Maintainability
*** 可运维性
**** 方便运营团队来保持系统平稳运行
*** 简单性
**** 简化系统复杂度，使新工程师能够轻松理解系统
*** 可演化性
**** 后续工程师能够轻松地对系统进行改进，并根据需求变化将其适配到非典型场景


@endmindmap
