@startmindmap
'https://plantuml.com/mindmap-diagram

caption CHAPTER 2
title 数据模型与查询语言

* 关系模型和文档模型
** 关系模型


** 文档模型

** 关系数据库和文档数据库变得越来越来越相近，\n数据模型可以相互补充

* 数据查询语言
** 命令式查询语言
*** 很多常见编程语言都是命令式

** 声明式查询语言
*** SQL是声明式查询语言，只需指定所需数据模式，\n结果满足什么条件，以及如何转换数据（例如排序、分组和聚合）
*** 比命令式API更加简洁和易使用，它对外隐藏了数据库引擎的很多实现细节，\n这样数据库能在不改变查询语句的情况下提高性能
*** 声明式查询语言不仅限于SQL
**** CSS选择器也是声明式查询语言
*** 使用声明式CSS样式表比JavaScript命令式的操作样式要好得多\n数据中，SQS声明式查询比命令式查询APIs要好得多





@endmindmap
