@startmindmap
'https://plantuml.com/mindmap-diagram

caption figure 1
title DDIA MindMap

* DDIA
** Reliability
*** 充分的测试
**** 测试工具: Netflix Chaos Monkey Test
**** 从单元测试 -> 全系统功能测试 -> 手动测试
** Scalability
** Maintainability

header
My super header
endheader

center footer My super footer

legend right
  Short
  legend
endlegend
@endmindmap
