@startmindmap
'https://plantuml.com/mindmap-diagram

* 高并发系统
** 前端优化
*** CDN
*** 异步加载
*** 资源压缩
*** 浏览器缓存
*** 懒加载

** 后端优化
*** 负载均衡
**** Nginx请求分发到不同的机器，避免单点故障，支持动态扩容。
*** 服务拆分
**** 微服务架构，分离功能模块（如用户服务、支付服务），降低耦合
*** 缓存策略
**** redis缓存热点数据
**** 本地缓存（Caffeine）减少远程调用
*** 数据库优化
**** 分库分表：水平分片（如按用户ID哈希）处理大数据表；垂直分表拆分大字段
**** 读写分离
*** 异步处理
**** 消息队列解耦耗时操作（如日志、邮件发送），提高响应速度
*** 连接池与线程池
**** 使用HikariCP数据库连接池、Java ThreadPoolExecutor，复用资源，避免创建开销
*** 地理分布
**** 多机房部署，结合DNS或全局负载均衡（如AWS Global Accelerator）,减少延迟
*** 熔断机制
**** 熔断（如Hystrix）、降级（非核心功能兜底）、自动扩缩（如Kubernetes）
** 监控与测试
*** 监控工具：Prometheus + Grafana跟踪QPS、延迟
*** 压测：使用JMeter或k6模拟高负载，验证优化效果
@endmindmap
